<a href="https://colab.research.google.com/github/Maria-kvetsko/weather_preddiction/blob/main/02_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/drive/MyDrive/weather_preddiction/data/open_meteo.csv')

In [3]:
data.isna().sum()

location_id                 0
time                        0
temperature_2m (°C)         0
relative_humidity_2m (%)    0
precipitation (mm)          0
rain (mm)                   0
snowfall (cm)               0
snow_depth (m)              0
pressure_msl (hPa)          0
cloud_cover (%)             0
cloud_cover_low (%)         0
cloud_cover_mid (%)         0
cloud_cover_high (%)        0
wind_speed_10m (km/h)       0
wind_speed_100m (km/h)      0
wind_direction_10m (°)      0
wind_direction_100m (°)     0
wind_gusts_10m (km/h)       0
dtype: int64

In [4]:
data['time'] = pd.to_datetime(data['time'])

In [5]:
data.head()

,location_id,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),snowfall (cm),snow_depth (m),pressure_msl (hPa),cloud_cover (%),cloud_cover_low (%),cloud_cover_mid (%),cloud_cover_high (%),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h)
0,0,2016-01-31 00:00:00,1.6,86,0.0,0.0,0.0,0.05,1013.1,98,13,29,96,18.8,36.3,206,212,32.8
1,0,2016-01-31 01:00:00,1.3,88,0.0,0.0,0.0,0.05,1012.0,98,8,20,97,19.3,36.2,201,208,32.4
2,0,2016-01-31 02:00:00,1.1,91,0.0,0.0,0.0,0.05,1011.0,100,9,20,100,20.2,37.1,199,204,34.6
3,0,2016-01-31 03:00:00,0.9,92,0.0,0.0,0.0,0.05,1009.9,100,8,4,100,21.2,38.4,198,203,37.4
4,0,2016-01-31 04:00:00,0.6,92,0.0,0.0,0.0,0.05,1008.7,98,13,16,97,21.9,38.7,194,200,39.2

In [6]:
data['year'] = data['time'].dt.year
data['month'] = data['time'].dt.month
data['day'] = data['time'].dt.day
data['hour'] = data['time'].dt.hour

In [8]:
data.head()

,location_id,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),snowfall (cm),snow_depth (m),pressure_msl (hPa),cloud_cover (%),...,cloud_cover_high (%),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),year,month,day,hour
0,0,2016-01-31 00:00:00,1.6,86,0.0,0.0,0.0,0.05,1013.1,98,...,96,18.8,36.3,206,212,32.8,2016,1,31,0
1,0,2016-01-31 01:00:00,1.3,88,0.0,0.0,0.0,0.05,1012.0,98,...,97,19.3,36.2,201,208,32.4,2016,1,31,1
2,0,2016-01-31 02:00:00,1.1,91,0.0,0.0,0.0,0.05,1011.0,100,...,100,20.2,37.1,199,204,34.6,2016,1,31,2
3,0,2016-01-31 03:00:00,0.9,92,0.0,0.0,0.0,0.05,1009.9,100,...,100,21.2,38.4,198,203,37.4,2016,1,31,3
4,0,2016-01-31 04:00:00,0.6,92,0.0,0.0,0.0,0.05,1008.7,98,...,97,21.9,38.7,194,200,39.2,2016,1,31,4

In [10]:
data.describe().round(1)

,location_id,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),snowfall (cm),snow_depth (m),pressure_msl (hPa),cloud_cover (%),...,cloud_cover_high (%),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),year,month,day,hour
count,1841616.0,1841616,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,...,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0,1841616.0
mean,10.0,2021-01-30 23:29:59.999999744,10.3,73.3,0.1,0.1,0.0,0.0,1016.6,62.8,...,36.0,12.5,21.0,192.6,192.9,24.8,2020.6,6.5,15.7,11.5
min,0.0,2016-01-31 00:00:00,-25.8,11.0,0.0,0.0,0.0,0.0,974.6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.7,2016.0,1.0,1.0,0.0
25%,5.0,2018-08-01 11:45:00,2.2,60.0,0.0,0.0,0.0,0.0,1011.2,18.0,...,0.0,7.9,14.3,106.0,107.0,16.2,2018.0,4.0,8.0,5.8
50%,10.0,2021-01-30 23:30:00,10.0,77.0,0.0,0.0,0.0,0.0,1016.1,85.0,...,6.0,11.5,20.6,196.0,196.0,23.4,2021.0,7.0,16.0,11.5
75%,15.0,2023-08-02 11:15:00,18.1,89.0,0.0,0.0,0.0,0.0,1021.7,100.0,...,89.0,16.2,26.9,288.0,289.0,32.0,2023.0,10.0,23.0,17.2
max,20.0,2026-01-31 23:00:00,39.5,100.0,34.7,34.7,4.4,0.6,1049.3,100.0,...,100.0,58.3,85.0,360.0,360.0,101.9,2026.0,12.0,31.0,23.0
std,6.1,NaN,9.8,18.3,0.3,0.3,0.1,0.1,8.2,40.5,...,42.3,6.0,9.4,104.3,104.4,11.3,2.9,3.4,8.8,6.9

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1841616 entries, 0 to 1841615
Data columns (total 22 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location_id               int64
 1   time                      datetime64[ns]
 2   temperature_2m (°C)       float64
 3   relative_humidity_2m (%)  int64
 4   precipitation (mm)        float64
 5   rain (mm)                 float64
 6   snowfall (cm)             float64
 7   snow_depth (m)            float64
 8   pressure_msl (hPa)        float64
 9   cloud_cover (%)           int64
 10  cloud_cover_low (%)       int64
 11  cloud_cover_mid (%)       int64
 12  cloud_cover_high (%)      int64
 13  wind_speed_10m (km/h)     float64
 14  wind_speed_100m (km/h)    float64
 15  wind_direction_10m (°)    int64
 16  wind_direction_100m (°)   int64
 17  wind_gusts_10m (km/h)     float64
 18  year                      int32
 19  month                     int32
 20  day                       int32
 21  hour                      int32
dtypes: datetime64[ns](1), float64(9), int32(4), int64(8)
memory usage: 281.0 MB

In [12]:
data.drop(['cloud_cover_low (%)', 'cloud_cover_mid (%)', 'cloud_cover_high (%)', 'wind_speed_100m (km/h)', 'wind_direction_100m (°)', 'wind_gusts_10m (km/h)'], axis=True)

,location_id,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),snowfall (cm),snow_depth (m),pressure_msl (hPa),cloud_cover (%),wind_speed_10m (km/h),wind_direction_10m (°),year,month,day,hour
0,0,2016-01-31 00:00:00,1.6,86,0.0,0.0,0.0,0.05,1013.1,98,18.8,206,2016,1,31,0
1,0,2016-01-31 01:00:00,1.3,88,0.0,0.0,0.0,0.05,1012.0,98,19.3,201,2016,1,31,1
2,0,2016-01-31 02:00:00,1.1,91,0.0,0.0,0.0,0.05,1011.0,100,20.2,199,2016,1,31,2
3,0,2016-01-31 03:00:00,0.9,92,0.0,0.0,0.0,0.05,1009.9,100,21.2,198,2016,1,31,3
4,0,2016-01-31 04:00:00,0.6,92,0.0,0.0,0.0,0.05,1008.7,98,21.9,194,2016,1,31,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841611,20,2026-01-31 19:00:00,-13.8,77,0.0,0.0,0.0,0.09,1021.5,0,12.9,53,2026,1,31,19
1841612,20,2026-01-31 20:00:00,-14.4,78,0.0,0.0,0.0,0.09,1022.1,0,11.3,53,2026,1,31,20
1841613,20,2026-01-31 21:00:00,-15.1,79,0.0,0.0,0.0,0.09,1022.7,0,10.0,54,2026,1,31,21
1841614,20,2026-01-31 22:00:00,-15.8,81,0.0,0.0,0.0,0.09,1022.9,0,9.6,52,2026,1,31,22
1841615,20,2026-01-31 23:00:00,-16.2,81,0.0,0.0,0.0,0.09,1023.2,0,9.8,50,2026,1,31,23

In [13]:
data.drop_duplicates()

,location_id,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),snowfall (cm),snow_depth (m),pressure_msl (hPa),cloud_cover (%),...,cloud_cover_high (%),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),year,month,day,hour
0,0,2016-01-31 00:00:00,1.6,86,0.0,0.0,0.0,0.05,1013.1,98,...,96,18.8,36.3,206,212,32.8,2016,1,31,0
1,0,2016-01-31 01:00:00,1.3,88,0.0,0.0,0.0,0.05,1012.0,98,...,97,19.3,36.2,201,208,32.4,2016,1,31,1
2,0,2016-01-31 02:00:00,1.1,91,0.0,0.0,0.0,0.05,1011.0,100,...,100,20.2,37.1,199,204,34.6,2016,1,31,2
3,0,2016-01-31 03:00:00,0.9,92,0.0,0.0,0.0,0.05,1009.9,100,...,100,21.2,38.4,198,203,37.4,2016,1,31,3
4,0,2016-01-31 04:00:00,0.6,92,0.0,0.0,0.0,0.05,1008.7,98,...,97,21.9,38.7,194,200,39.2,2016,1,31,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841611,20,2026-01-31 19:00:00,-13.8,77,0.0,0.0,0.0,0.09,1021.5,0,...,0,12.9,27.7,53,59,24.1,2026,1,31,19
1841612,20,2026-01-31 20:00:00,-14.4,78,0.0,0.0,0.0,0.09,1022.1,0,...,0,11.3,26.2,53,60,22.3,2026,1,31,20
1841613,20,2026-01-31 21:00:00,-15.1,79,0.0,0.0,0.0,0.09,1022.7,0,...,0,10.0,24.8,54,60,19.4,2026,1,31,21
1841614,20,2026-01-31 22:00:00,-15.8,81,0.0,0.0,0.0,0.09,1022.9,0,...,0,9.6,24.2,52,60,17.3,2026,1,31,22
1841615,20,2026-01-31 23:00:00,-16.2,81,0.0,0.0,0.0,0.09,1023.2,0,...,0,9.8,24.5,50,59,16.6,2026,1,31,23

In [15]:
data['location_id'].value_counts()

location_id
0     87696
1     87696
2     87696
3     87696
4     87696
5     87696
6     87696
7     87696
8     87696
9     87696
10    87696
11    87696
12    87696
13    87696
14    87696
15    87696
16    87696
17    87696
18    87696
19    87696
20    87696
Name: count, dtype: int64

In [19]:
data.to_csv('/content/drive/MyDrive/weather_preddiction/data/cleaned.csv',index=False)